language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: Nj2btGnS96zggk1IixSSYvG0wNfH1K68mleHjjhvGpz1Zo/vl18ghosI0I+hgml9OEW7Xn4c3rAVRbdHSo1LMq95VYJ5Jn4DqCISvFpFjbFm02lIEJ5/rs93z8Xx18UMapHQsJEQpSmBvSSbFhcNz8Ab5YK0N5gHr/tkQT0BFs8=
