language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: Um97JxrG7rQc0BS7BvkUBGwEVG2rEwj9WGrMffZKxAcQHjInaONI4awdvD2VTNOd3rX2woMjVoGOZty9lipi/3dZI+FXTjDS4VKICa70Ct47RY3wfb5ipsHSsSJGPbHhBE5tGB9TUmbgh/P/cNuJmaXG6cWp+rk3mC0zEP1aee8=